server:
  port: 8890
  tomcat:
    uri-encoding: utf-8
spring:
#热部署生效
  profiles:
    active: test
  devtools:
    restart:
      enabled: true
      additional-paths: src/mian/java
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/basedata?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: root
          driver-class-name: com.mysql.jdbc.Driver
          password: 1234567
          dbcp2:
            max-idle: 10
            max-wait-millis: 10000
            min-idle: 5
            initial-size: 5
        slave_1:
          username: root
          password: 1234567
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/sys?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          dbcp2:
            max-idle: 10
            max-wait-millis: 10000
            min-idle: 5
            initial-size: 5
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:E:/
#  data:
#    mongodb:
#      database: test

  jpa:
    show-sql: true

#  mvc:
#    static-path-pattern: /**
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#    cache: false
#  resources:
#    chain:
#      strategy:
#        content:
#          enabled: true
#          paths: /**

#  spring.resources.chain.strategy.content.enabled=true
#  spring.resources.chain.strategy.content.paths=/**

#    # 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
## Mybatis配置

#mybatis.mapper-locations=classpath:mapper/*.xml
mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xmlf
    global-config:
      db-config:
        field-strategy: ignored
    configuration:
      log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
#    global-config:
#      db-config:
#        id-type: auto
    type-aliases-package: cn/wmyskz/springboot/**/entity

#实体扫描，多个package用逗号或者分号分隔

logging:
  config: classpath:log4j2.xml

